---
title: "Report for BC pollinator app"
output: html_document
params:
  plot_rep: NA
  chosen_things: NA
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Selected Options


|**Region** |**Type of name**|**What do you want to do?**|
|---|---|---|
|`r params$chosen_things$region`|`r params$chosen_things$name_type`|`r params$chosen_things$action_type`|



```{r}
if(params$chosen_things$action_type == "Build Network"){
  
  if(params$chosen_things$net_type == 'Plant'){
     sp <- params$chosen_things$plants
  }else if(params$chosen_things$net_type == 'Pollinator'){
    sp <- params$chosen_things$bees
  }
  
  sp <- paste(str_replace(sp, "\n", " "), collapse = ", ")
   second_options <- data.frame(type_net = params$chosen_things$net_type, species = sp)
   colnames(second_options) <- c("Type of Network", "Species chosen")
}else if(params$chosen_things$action_type == "Get plants"){
  if(is.null(params$chosen_things$native)){
    native <- "None selected"
  }else{
    native <- params$chosen_things$native
  }
  if(is.null(params$chosen_things$shrub)){
    shrub <- "None selected"
  }else{
    shrub <-params$chosen_things$shrub
  }
  if(params$chosen_things$maximizer == "Phenological coverage"){
    second_options <- data.frame(maximizer = params$chosen_things$maximizer, native_p = native, plant_type = shrub, n_plant = params$chosen_things$n_plants, week1 = params$chosen_things$dateRange1[1], week2 = params$chosen_things$dateRange2[2])
  colnames(second_options) <- c("How do we select plants?", "Native plants", "Type of plants", "Number of plants", "Flowering range start", "Flowering range end")
  }else{
    second_options <- data.frame(maximizer = params$chosen_things$maximizer, native_p = native, plant_type = shrub, n_plant = params$chosen_things$n_plants)
  colnames(second_options) <- c("How do we select plants?", "Native plants", "Type of plants", "Number of plants")
  }
}else if(params$chosen_things$action_type == "Support crop"){
  if(is.null(params$chosen_things$native_2)){
    native_2 <- "None selected"
  }else{
    native_2 <- params$chosen_things$native_2
  }
  if(is.null(params$chosen_things$shrub_2)){
    shrub_2 <- "None selected"
  }else{
    shrub_2 <-params$chosen_things$shrub_2
  }
  second_options <- data.frame(crop = params$chosen_things$crop, native_p = native_2, plant_type = shrub_2, n_plant = params$chosen_things$n_plants_2, overlap = params$chosen_things$overlap_2, week1 = params$chosen_things$dateRange2[1], week2 = params$chosen_things$dateRange2[2])
  colnames(second_options) <- c("What crop do you want to support?", "Native plants", "Type of plants", "Number of plants", "Should plants overlap with crop?", "Flowering range start", "Flowering range end")
}
knitr::kable(second_options)
```



## Figure


```{r fig.width = 6}
params$plot_rep
```


## Summary

```{r message=FALSE}
output_dir <- "/home/lmguzman/ShinyApps/bc_bees/"
#output_dir <- "/Users/lmguzman/Documents/SFU/bc_bees"
file_name <- "tmp/temp_output.rds"
db <- read.csv(file.path(output_dir, "data/site_net_loc_fil_links.csv"), stringsAsFactors = FALSE)

temp_data <- readRDS(file.path(output_dir, file_name))

if(params$chosen_things$action_type == "Build Network"){
  if(params$chosen_things$net_type == "Pollinator" & length(params$chosen_things$bees) == 1){
    output_table_2 <- data.frame(temp_data) %>% 
      dplyr::select(-`X.`) %>% 
      tibble::rownames_to_column(var = 'Plant.species') %>% 
      dplyr::mutate(Plant.species = str_replace(Plant.species, "\n", " "))
  }else if(params$chosen_things$net_type == "Plant" & length(params$chosen_things$plants) == 1){
    output_table_2 <- data.frame(temp_data) %>% 
      tibble::rownames_to_column(var = 'Plant.species') %>% 
      dplyr::mutate(Plant.species = str_replace(Plant.species, "\n", " ")) %>% 
      slice(1)
  }else{
    output_table_2 <- data.frame(temp_data) %>% 
      tibble::rownames_to_column(var = 'Plant.species') %>% 
      dplyr::mutate(Plant.species = str_replace(Plant.species, "\n", " ")) 
  }
  output_table <- output_table_2[order(output_table_2[,2], decreasing = TRUE),]
  colnames(output_table) <- str_replace(colnames(output_table), "\\.", " ")
}else if(params$chosen_things$action_type == "Get plants" & (params$chosen_things$maximizer == "Pollinator abundance" | params$chosen_things$maximizer == "Pollinator diversity")){
  plant_trait <- db %>% 
    dplyr::select(plant_sp, plant_native, plant_invasive2, plant_life_form) %>% unique() %>% 
    dplyr::mutate(plant_sp = str_replace(plant_sp, "\n", " "))
  
  output_table <- temp_data %>% 
    dplyr::select(plant_sp, bee_guild_otro) %>% 
    dplyr::mutate(plant_sp = str_replace(plant_sp, "\n", " ")) %>% 
    group_by(plant_sp, bee_guild_otro) %>% 
    summarise(n_obs = n()) %>% 
    left_join(plant_trait)

  colnames(output_table)  <- c("Plant species", "Pollinator guild", "Number of observations", "Plant native", "Plant Invasiveness", "Plant life form")
}else if((params$chosen_things$action_type == "Get plants" & params$chosen_things$maximizer == "Phenological coverage") | params$chosen_things$action_type == "Support crop"){
  
    output_table <- temp_data %>% 
      dplyr::mutate(plant_sp = str_replace(plant_sp, "\n", " ")) %>% 
      dplyr::mutate(week = paste("Week", week)) %>% 
      dplyr::mutate(active = 'yes') %>% 
      pivot_wider(names_from = week, values_from = active, values_fill = list(active = 'no')) 
   colnames(output_table)[1:2] <- c("Plant species", "Plant common name")
  }

knitr::kable(output_table, row.names = FALSE)
```

Thank you for using our app!
